image:
    file: .gitpod.Dockerfile
checkoutLocation: "~/config/gitpod"
workspaceLocation: "ws"
tasks:
    - init: echo 'y' | sdk i java 8.0.252-amzn
      command: echo 'y' | sdkmanager --licenses
      command: echo 'y' | sdkmanager --update
