image:
    file: .gitpod.Dockerfile

workspaceLocation: "ws"

tasks:
    - command: |
        echo 'y' | sdk i java 8.0.282-open
        yes | sdkmanager --licenses
        yes | sdkmanager --update
        sdk use java 11.0.11.fx-zulu
