image:
    file: .gitpod.Dockerfile
checkoutLocation: "~/gitpod_ide"
workspaceLocation: "."
tasks:
    - init: yes | sdk i java 8.0.232-amzn
      command: yes | sdkmanager --licenses
      command: yes | sdkmanager --update
