image:
    file: .gitpod.Dockerfile

checkoutLocation: ".gpconfig"
workspaceLocation: "."

tasks:
    - command: |
        echo 'y' | sdk i java 8.0.282-open
        yes | sdkmanager --licenses
        yes | sdkmanager --update
